name: Deploy Pipeline in Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Download a Build Artifact
        users: actions/download-artifact@v3.0.0
        with:
          name: builded

      - name: Docker Login
        users: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # https://github.com/organizations/<org-name>/settings/secrets/actions / https://github.com/<account-name>/<repo-name>/settings/secrets/actions
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker images
        users: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/image-name:${{ github.ref_name }} # user/iamge:branch
