name: Deploy Pipeline with Metadata Actions

on:
  push:
    branches:
      - "release/*"
    tags:
      - "v*"

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # images: ghcr.io/thedatabaseme/hello-world
          images: viniciusfreitasrj17/pipeline-metadata-actions
          # flavor: latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      # - name: Build and tag docker image
      #   run: |
      #     docker build --tag=${{ steps.meta.outputs.labels }}:${{ steps.meta.outputs.tags }} .

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          # registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push image to Docker Hub
      #   run: |
      #     docker push ${{ steps.meta.outputs.labels }}:${{ steps.meta.outputs.tags }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}