name: Deploy Pipeline with Metadata Actions for Homolog

env:
  CLUSTER: CLUSTER-ID
  DEPLOYMENT: DEPLOYMENT-NAME
  NAMESPACE: NS
  
on:
  push:
    branches: 
      - "staging"

jobs:
  deploy-to-docker:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          # registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: viniciusfreitasrj17/pipeline-metadata-actions:staging
          # target: prod

  # deploy-to-k8s:
  #   name: Rollout K8S in DO
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
  #     - name: Save DigitalOcean kubeconfig
  #       run: doctl kubernetes cluster kubeconfig save $CLUSTER

  #     - name: Update deployment
  #       run: kubectl rollout restart deployment $DEPLOYMENT --namespace=$NAMESPACE
